### ISSUE TITLE
no matching distribution error

### ISSUE THREAD

**Issue by fanux** [cloudfoundry-samples/pong_matcher_django#1]
No matching distribution found for mysql-connector-python==2.0.4 (from -r requirements.txt (line 7))
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
BuildpackCompileFailed

**Comment by howardjones** [comment]
"MySQL Connector/Python currently not available from PyPI"
https://geert.vanderkelen.org/2016/cpy-and-pypi/

Although I don't know how the suggested solutions (apt/yum or download) will help with CF apps.

**Comment by howardjones** [comment]
Also, there was another problem with static files where STATIC_ROOT was not defined.

My partially-assed solution: switch to postgres. Remove the mysql line from requirements.txt and create a postgresql instance instead of mysql:

```
cf create-service elephantsql turtle elephant
```

Modify manifest.yml to say 'elephant' instead of 'mysql'

And the following changes in pong_matcher_django/settings:

```
      'ENGINE': 'django.db.backends.postgresql_psycopg2',


  STATIC_URL = '/static/'
+ STATIC_ROOT = os.path.join(BASE_DIR, "static")
```

**Comment by animatedmax** [comment]
Hi @howardjones 

If you have a Contributor License Agreement (CLA) on-file with us, or you are already covered by a Corporate CLA, or if you'd like to sign one, we'd be happy to make your suggested changes to the code in this sample app -- just let us know!

Thank you!

**Comment by howardjones** [comment]
Two lines of configuration? It barely counts as "code".

I would have to talk to legal and HR which already sounds like a bad day...
